### ISSUE TITLE
Relationship between parsing and printing

### ISSUE THREAD

**Issue by andrejbauer** [andrejbauer/andromeda#10]
I would like to propose that the output from the pretty printer should be parsable. We can just ignore the annotations during parsing. The other issue is how to deal with the difference between a type and the type named by an element. When annotations are turned on with `Print.annotate`, `El` is printed explicitly, but that cannnot be parsed. Maybe we can just add `El` to the parser.

**Comment by christopherastone** [comment]
It looks like El is gone. Is this still an issue?

**Comment by andrejbauer** [comment]
We were seduced by @vladimirias to implement `Type : Type`. It actually makes everything much simpler. We do not even distinguish between the type-as-element and type-proper, but eventually we need to think about Tarski universes. That's when `El` will come back.

Note that the internal representation of types is `Ty e` where `e` is a term, so in a sense we have the inverse of `El`.

**Comment by andrejbauer** [comment]
Actually, our `Ty` is like `El`, so please disregard my claiming it's the inverse of `El`.

**Comment by andrejbauer** [comment]
We have forsaken every chance of output being parseable since the output is a different kind of animal (a type-theoretic judgement) than the input (a program).
