### ISSUE TITLE
Unify error messages `runtime` and `typing`

### ISSUE THREAD

**Issue by andrejbauer** [andrejbauer/andromeda#48]
It's possible to report either an `Error.runtime` or an `Error.typing` error, but there's probably no difference between these two, is there?

**Comment by christopherastone** [comment]
The only difference is in how the error is printed, e.g. "Typing Error: ...message..." vs. "Runtime error: ...message..."

**Comment by andrejbauer** [comment]
Oh, I see. We should use typing errors to indicate something is wrong with the terms and their types (i.e., the values we're computing), and runtime errors when there is a problem with the programming language (for instance, installing a bad hint).

**Comment by andrejbauer** [comment]
Closing but let's not forget the difference.
